name: Environment-variable
on:
  workflow_dispatch:
  
env:
  Day_of_week: Monday
jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Environment declaration
        run: echo "$Greeting $First_name. Today is $Day_of_week"
        env:
          First_name: Sheethalllll
